//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Online.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atlas.Online.Web.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Congratulations!&lt;/strong&gt;&lt;br&gt;Your Atlas Online loan will be in your account within the next few minutes..
        /// </summary>
        public static string Application_Complete {
            get {
                return ResourceManager.GetString("Application_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We apologise, but you application was unsuccessful this time.&lt;br&gt;Your application reference number: {0}..
        /// </summary>
        public static string Application_Declined {
            get {
                return ResourceManager.GetString("Application_Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that it is passed 3pm and so your loan will be paid over to you on the next working day..
        /// </summary>
        public static string Application_PassedCutOff {
            get {
                return ResourceManager.GetString("Application_PassedCutOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Congratulations&lt;/strong&gt;, on accepting your Atlas Online loan.&lt;br&gt;Your bank account is currently pending account verification.&lt;br&gt;You will be notified via email if more action is required..
        /// </summary>
        public static string Application_Pending {
            get {
                return ResourceManager.GetString("Application_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payout is pending as banks are currently closed. &lt;br/&gt; Your loan will be processed first thing in the morning..
        /// </summary>
        public static string Application_PendingBankCutOff {
            get {
                return ResourceManager.GetString("Application_PendingBankCutOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! &lt;br/&gt;
        ///Your Atlas Online loan will be paid out on the next working day..
        /// </summary>
        public static string Application_PendingHoliday {
            get {
                return ResourceManager.GetString("Application_PendingHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payout is pending as banks are currently closed. &lt;br/&gt; Your loan will be processed first thing in the morning..
        /// </summary>
        public static string Application_PendingNextWorkingDay {
            get {
                return ResourceManager.GetString("Application_PendingNextWorkingDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We apologise, but your application has been forwarded to our review department.&lt;br&gt;Your application reference number: {0}..
        /// </summary>
        public static string Application_Review {
            get {
                return ResourceManager.GetString("Application_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bank verification has failed. Your bank account details have been locked and application declined. &lt;br&gt; Please contact Atlas Online if you believe this was done in error..
        /// </summary>
        public static string AVS_BankDetailsLocked {
            get {
                return ResourceManager.GetString("AVS_BankDetailsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bank details have been verified!.
        /// </summary>
        public static string AVS_BankDetailsPassed {
            get {
                return ResourceManager.GetString("AVS_BankDetailsPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your banking details are being verified. This process may take several minutes. In the mean time, you may continue with the rest of the application..
        /// </summary>
        public static string AVS_BankDetailsProcessing {
            get {
                return ResourceManager.GetString("AVS_BankDetailsProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are processing your banking details. You will be unable to make changes to them until this process completes. This process may take several minutes. Please feel free to continue with your application..
        /// </summary>
        public static string AVS_BankDetailsProcessingConfirmVerify {
            get {
                return ResourceManager.GetString("AVS_BankDetailsProcessingConfirmVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your banking details are being verified. This process may take several minutes..
        /// </summary>
        public static string AVS_BankDetailsProcessingMyAccount {
            get {
                return ResourceManager.GetString("AVS_BankDetailsProcessingMyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent!|Your message has been sent to one of our helpful operators.&lt;br&gt;You will here back from us soon..
        /// </summary>
        public static string Contact_MessageSent {
            get {
                return ResourceManager.GetString("Contact_MessageSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset sent.|Please check your email for further instructions..
        /// </summary>
        public static string PasswordReset_Sent {
            get {
                return ResourceManager.GetString("PasswordReset_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset.|Click the button below to login with your new password..
        /// </summary>
        public static string PasswordReset_Success {
            get {
                return ResourceManager.GetString("PasswordReset_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message sent!|Your question has been sent to one of our helpful operators.&lt;br&gt;You will here back from us soon..
        /// </summary>
        public static string Question_MessageSent {
            get {
                return ResourceManager.GetString("Question_MessageSent", resourceCulture);
            }
        }
    }
}
