//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Online.Node.AffordabilityNode.OrchestrationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Atlas.Orchestration.Server.Structures")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Atlas.Online.Node.AffordabilityNode.OrchestrationService.Address> AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Atlas.Online.Node.AffordabilityNode.OrchestrationService.BankDetail BankDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Atlas.Online.Node.AffordabilityNode.OrchestrationService.Contact> ContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Atlas.Online.Node.AffordabilityNode.OrchestrationService.Employer EmployerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Atlas.Enumerators.General.Gender GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Atlas.Enumerators.General.Host HostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Atlas.Online.Node.AffordabilityNode.OrchestrationService.Relation RelationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Atlas.Online.Node.AffordabilityNode.OrchestrationService.Address> Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Online.Node.AffordabilityNode.OrchestrationService.BankDetail BankDetail {
            get {
                return this.BankDetailField;
            }
            set {
                if ((object.ReferenceEquals(this.BankDetailField, value) != true)) {
                    this.BankDetailField = value;
                    this.RaisePropertyChanged("BankDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Atlas.Online.Node.AffordabilityNode.OrchestrationService.Contact> Contacts {
            get {
                return this.ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsField, value) != true)) {
                    this.ContactsField = value;
                    this.RaisePropertyChanged("Contacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Online.Node.AffordabilityNode.OrchestrationService.Employer Employer {
            get {
                return this.EmployerField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployerField, value) != true)) {
                    this.EmployerField = value;
                    this.RaisePropertyChanged("Employer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Enumerators.General.Gender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Enumerators.General.Host Host {
            get {
                return this.HostField;
            }
            set {
                if ((this.HostField.Equals(value) != true)) {
                    this.HostField = value;
                    this.RaisePropertyChanged("Host");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNo {
            get {
                return this.IdNoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdNoField, value) != true)) {
                    this.IdNoField = value;
                    this.RaisePropertyChanged("IdNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Online.Node.AffordabilityNode.OrchestrationService.Relation Relation {
            get {
                return this.RelationField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationField, value) != true)) {
                    this.RelationField = value;
                    this.RaisePropertyChanged("Relation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankDetail", Namespace="http://schemas.datacontract.org/2004/07/Atlas.Orchestration.Server.Structures")]
    [System.SerializableAttribute()]
    public partial class BankDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Atlas.Enumerators.General.BankAccountType AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Atlas.Enumerators.General.BankName BankField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Atlas.Enumerators.General.BankPeriod PeriodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNo {
            get {
                return this.AccountNoField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNoField, value) != true)) {
                    this.AccountNoField = value;
                    this.RaisePropertyChanged("AccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Enumerators.General.BankAccountType AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((this.AccountTypeField.Equals(value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Enumerators.General.BankName Bank {
            get {
                return this.BankField;
            }
            set {
                if ((this.BankField.Equals(value) != true)) {
                    this.BankField = value;
                    this.RaisePropertyChanged("Bank");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Enumerators.General.BankPeriod Period {
            get {
                return this.PeriodField;
            }
            set {
                if ((this.PeriodField.Equals(value) != true)) {
                    this.PeriodField = value;
                    this.RaisePropertyChanged("Period");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employer", Namespace="http://schemas.datacontract.org/2004/07/Atlas.Orchestration.Server.Structures")]
    [System.SerializableAttribute()]
    public partial class Employer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Atlas.Online.Node.AffordabilityNode.OrchestrationService.Address> AddressesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Atlas.Online.Node.AffordabilityNode.OrchestrationService.Contact> ContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Atlas.Online.Node.AffordabilityNode.OrchestrationService.Address> Addresses {
            get {
                return this.AddressesField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressesField, value) != true)) {
                    this.AddressesField = value;
                    this.RaisePropertyChanged("Addresses");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Atlas.Online.Node.AffordabilityNode.OrchestrationService.Contact> Contacts {
            get {
                return this.ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsField, value) != true)) {
                    this.ContactsField = value;
                    this.RaisePropertyChanged("Contacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relation", Namespace="http://schemas.datacontract.org/2004/07/Atlas.Orchestration.Server.Structures")]
    [System.SerializableAttribute()]
    public partial class Relation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Atlas.Online.Node.AffordabilityNode.OrchestrationService.Contact> ContactsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Atlas.Enumerators.General.RelationType RelationTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Atlas.Online.Node.AffordabilityNode.OrchestrationService.Contact> Contacts {
            get {
                return this.ContactsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactsField, value) != true)) {
                    this.ContactsField = value;
                    this.RaisePropertyChanged("Contacts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Enumerators.General.RelationType RelationType {
            get {
                return this.RelationTypeField;
            }
            set {
                if ((this.RelationTypeField.Equals(value) != true)) {
                    this.RelationTypeField = value;
                    this.RaisePropertyChanged("RelationType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/Atlas.Orchestration.Server.Structures")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Atlas.Enumerators.General.AddressType AddressTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Atlas.Enumerators.General.Province ProvinceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Enumerators.General.AddressType AddressType {
            get {
                return this.AddressTypeField;
            }
            set {
                if ((this.AddressTypeField.Equals(value) != true)) {
                    this.AddressTypeField = value;
                    this.RaisePropertyChanged("AddressType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line1 {
            get {
                return this.Line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line1Field, value) != true)) {
                    this.Line1Field = value;
                    this.RaisePropertyChanged("Line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line2 {
            get {
                return this.Line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line2Field, value) != true)) {
                    this.Line2Field = value;
                    this.RaisePropertyChanged("Line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line3 {
            get {
                return this.Line3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line3Field, value) != true)) {
                    this.Line3Field = value;
                    this.RaisePropertyChanged("Line3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line4 {
            get {
                return this.Line4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line4Field, value) != true)) {
                    this.Line4Field = value;
                    this.RaisePropertyChanged("Line4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Enumerators.General.Province Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((this.ProvinceField.Equals(value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contact", Namespace="http://schemas.datacontract.org/2004/07/Atlas.Orchestration.Server.Structures")]
    [System.SerializableAttribute()]
    public partial class Contact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Atlas.Enumerators.General.ContactType ContactTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Enumerators.General.ContactType ContactType {
            get {
                return this.ContactTypeField;
            }
            set {
                if ((this.ContactTypeField.Equals(value) != true)) {
                    this.ContactTypeField = value;
                    this.RaisePropertyChanged("ContactType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TupleOflonglong", Namespace="http://schemas.datacontract.org/2004/07/System")]
    [System.SerializableAttribute()]
    public partial class TupleOflonglong : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long m_Item1Field;
        
        private long m_Item2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long m_Item1 {
            get {
                return this.m_Item1Field;
            }
            set {
                if ((this.m_Item1Field.Equals(value) != true)) {
                    this.m_Item1Field = value;
                    this.RaisePropertyChanged("m_Item1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long m_Item2 {
            get {
                return this.m_Item2Field;
            }
            set {
                if ((this.m_Item2Field.Equals(value) != true)) {
                    this.m_Item2Field = value;
                    this.RaisePropertyChanged("m_Item2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TupleOfintstring", Namespace="http://schemas.datacontract.org/2004/07/System")]
    [System.SerializableAttribute()]
    public partial class TupleOfintstring : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int m_Item1Field;
        
        private string m_Item2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int m_Item1 {
            get {
                return this.m_Item1Field;
            }
            set {
                if ((this.m_Item1Field.Equals(value) != true)) {
                    this.m_Item1Field = value;
                    this.RaisePropertyChanged("m_Item1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_Item2 {
            get {
                return this.m_Item2Field;
            }
            set {
                if ((object.ReferenceEquals(this.m_Item2Field, value) != true)) {
                    this.m_Item2Field = value;
                    this.RaisePropertyChanged("m_Item2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrchestrationService.IOrchestrationService")]
    public interface IOrchestrationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetByIdNo", ReplyAction="http://tempuri.org/IOrchestrationService/GetByIdNoResponse")]
        Atlas.Domain.DTO.PER_PersonDTO GetByIdNo(string idNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetByIdNo", ReplyAction="http://tempuri.org/IOrchestrationService/GetByIdNoResponse")]
        System.Threading.Tasks.Task<Atlas.Domain.DTO.PER_PersonDTO> GetByIdNoAsync(string idNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/Save", ReplyAction="http://tempuri.org/IOrchestrationService/SaveResponse")]
        Atlas.Online.Node.AffordabilityNode.OrchestrationService.TupleOflonglong Save(Atlas.Online.Node.AffordabilityNode.OrchestrationService.Person client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/Save", ReplyAction="http://tempuri.org/IOrchestrationService/SaveResponse")]
        System.Threading.Tasks.Task<Atlas.Online.Node.AffordabilityNode.OrchestrationService.TupleOflonglong> SaveAsync(Atlas.Online.Node.AffordabilityNode.OrchestrationService.Person client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetbyPk", ReplyAction="http://tempuri.org/IOrchestrationService/GetbyPkResponse")]
        Atlas.Domain.DTO.PER_PersonDTO GetbyPk(long pk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetbyPk", ReplyAction="http://tempuri.org/IOrchestrationService/GetbyPkResponse")]
        System.Threading.Tasks.Task<Atlas.Domain.DTO.PER_PersonDTO> GetbyPkAsync(long pk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetBankDetails", ReplyAction="http://tempuri.org/IOrchestrationService/GetBankDetailsResponse")]
        System.Collections.Generic.List<Atlas.Domain.DTO.BankDetailDTO> GetBankDetails(System.Nullable<long> personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetBankDetails", ReplyAction="http://tempuri.org/IOrchestrationService/GetBankDetailsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Atlas.Domain.DTO.BankDetailDTO>> GetBankDetailsAsync(System.Nullable<long> personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetBankDetail", ReplyAction="http://tempuri.org/IOrchestrationService/GetBankDetailResponse")]
        Atlas.Domain.DTO.BankDetailDTO GetBankDetail(long personId, string accountNo, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetBankDetail", ReplyAction="http://tempuri.org/IOrchestrationService/GetBankDetailResponse")]
        System.Threading.Tasks.Task<Atlas.Domain.DTO.BankDetailDTO> GetBankDetailAsync(long personId, string accountNo, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetAccountVerification", ReplyAction="http://tempuri.org/IOrchestrationService/GetAccountVerificationResponse")]
        Atlas.Domain.Structures.AccountVerification GetAccountVerification(string idNo, string accountNo, Atlas.Enumerators.General.BankName bank, int daysAgo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetAccountVerification", ReplyAction="http://tempuri.org/IOrchestrationService/GetAccountVerificationResponse")]
        System.Threading.Tasks.Task<Atlas.Domain.Structures.AccountVerification> GetAccountVerificationAsync(string idNo, string accountNo, Atlas.Enumerators.General.BankName bank, int daysAgo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetAccountVerificationById", ReplyAction="http://tempuri.org/IOrchestrationService/GetAccountVerificationByIdResponse")]
        Atlas.Domain.Structures.AccountVerification GetAccountVerificationById(long transactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetAccountVerificationById", ReplyAction="http://tempuri.org/IOrchestrationService/GetAccountVerificationByIdResponse")]
        System.Threading.Tasks.Task<Atlas.Domain.Structures.AccountVerification> GetAccountVerificationByIdAsync(long transactionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetBankDetailByDetailId", ReplyAction="http://tempuri.org/IOrchestrationService/GetBankDetailByDetailIdResponse")]
        Atlas.Domain.DTO.BankDetailDTO GetBankDetailByDetailId(long personId, long bankDetailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetBankDetailByDetailId", ReplyAction="http://tempuri.org/IOrchestrationService/GetBankDetailByDetailIdResponse")]
        System.Threading.Tasks.Task<Atlas.Domain.DTO.BankDetailDTO> GetBankDetailByDetailIdAsync(long personId, long bankDetailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/SaveBank", ReplyAction="http://tempuri.org/IOrchestrationService/SaveBankResponse")]
        System.Nullable<long> SaveBank(long personId, Atlas.Enumerators.General.BankName bank, Atlas.Enumerators.General.BankAccountType accountType, string accountName, string accountNo, Atlas.Enumerators.General.BankPeriod accountPeriod, string branchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/SaveBank", ReplyAction="http://tempuri.org/IOrchestrationService/SaveBankResponse")]
        System.Threading.Tasks.Task<System.Nullable<long>> SaveBankAsync(long personId, Atlas.Enumerators.General.BankName bank, Atlas.Enumerators.General.BankAccountType accountType, string accountName, string accountNo, Atlas.Enumerators.General.BankPeriod accountPeriod, string branchCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/UpdateBankDetails", ReplyAction="http://tempuri.org/IOrchestrationService/UpdateBankDetailsResponse")]
        void UpdateBankDetails(long personId, long detailId, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/UpdateBankDetails", ReplyAction="http://tempuri.org/IOrchestrationService/UpdateBankDetailsResponse")]
        System.Threading.Tasks.Task UpdateBankDetailsAsync(long personId, long detailId, bool isActive);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GenerateOTP", ReplyAction="http://tempuri.org/IOrchestrationService/GenerateOTPResponse")]
        Atlas.Online.Node.AffordabilityNode.OrchestrationService.TupleOfintstring GenerateOTP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GenerateOTP", ReplyAction="http://tempuri.org/IOrchestrationService/GenerateOTPResponse")]
        System.Threading.Tasks.Task<Atlas.Online.Node.AffordabilityNode.OrchestrationService.TupleOfintstring> GenerateOTPAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/VerifyOTP", ReplyAction="http://tempuri.org/IOrchestrationService/VerifyOTPResponse")]
        bool VerifyOTP(string security, int otp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/VerifyOTP", ReplyAction="http://tempuri.org/IOrchestrationService/VerifyOTPResponse")]
        System.Threading.Tasks.Task<bool> VerifyOTPAsync(string security, int otp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetCompiledTemplate", ReplyAction="http://tempuri.org/IOrchestrationService/GetCompiledTemplateResponse")]
        string GetCompiledTemplate(Atlas.Enumerators.Notification.NotificationTemplate notificationTemplate, System.Collections.Generic.Dictionary<string, string> searchReplace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetCompiledTemplate", ReplyAction="http://tempuri.org/IOrchestrationService/GetCompiledTemplateResponse")]
        System.Threading.Tasks.Task<string> GetCompiledTemplateAsync(Atlas.Enumerators.Notification.NotificationTemplate notificationTemplate, System.Collections.Generic.Dictionary<string, string> searchReplace);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/CreatePerson", ReplyAction="http://tempuri.org/IOrchestrationService/CreatePersonResponse")]
        long CreatePerson(string firstName, string lastName, string idNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/CreatePerson", ReplyAction="http://tempuri.org/IOrchestrationService/CreatePersonResponse")]
        System.Threading.Tasks.Task<long> CreatePersonAsync(string firstName, string lastName, string idNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/CompanyPolicies", ReplyAction="http://tempuri.org/IOrchestrationService/CompanyPoliciesResponse")]
        System.Collections.Generic.List<Atlas.Enumerators.Account.Policy> CompanyPolicies(long accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/CompanyPolicies", ReplyAction="http://tempuri.org/IOrchestrationService/CompanyPoliciesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Atlas.Enumerators.Account.Policy>> CompanyPoliciesAsync(long accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/AccountPolicies", ReplyAction="http://tempuri.org/IOrchestrationService/AccountPoliciesResponse")]
        System.Collections.Generic.List<Atlas.Domain.DTO.ACC_PolicyDTO> AccountPolicies(long personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/AccountPolicies", ReplyAction="http://tempuri.org/IOrchestrationService/AccountPoliciesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Atlas.Domain.DTO.ACC_PolicyDTO>> AccountPoliciesAsync(long personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetReApplyDelay", ReplyAction="http://tempuri.org/IOrchestrationService/GetReApplyDelayResponse")]
        int GetReApplyDelay(long personId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrchestrationService/GetReApplyDelay", ReplyAction="http://tempuri.org/IOrchestrationService/GetReApplyDelayResponse")]
        System.Threading.Tasks.Task<int> GetReApplyDelayAsync(long personId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrchestrationServiceChannel : Atlas.Online.Node.AffordabilityNode.OrchestrationService.IOrchestrationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrchestrationServiceClient : System.ServiceModel.ClientBase<Atlas.Online.Node.AffordabilityNode.OrchestrationService.IOrchestrationService>, Atlas.Online.Node.AffordabilityNode.OrchestrationService.IOrchestrationService {
        
        public OrchestrationServiceClient() {
        }
        
        public OrchestrationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrchestrationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrchestrationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrchestrationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Atlas.Domain.DTO.PER_PersonDTO GetByIdNo(string idNo) {
            return base.Channel.GetByIdNo(idNo);
        }
        
        public System.Threading.Tasks.Task<Atlas.Domain.DTO.PER_PersonDTO> GetByIdNoAsync(string idNo) {
            return base.Channel.GetByIdNoAsync(idNo);
        }
        
        public Atlas.Online.Node.AffordabilityNode.OrchestrationService.TupleOflonglong Save(Atlas.Online.Node.AffordabilityNode.OrchestrationService.Person client) {
            return base.Channel.Save(client);
        }
        
        public System.Threading.Tasks.Task<Atlas.Online.Node.AffordabilityNode.OrchestrationService.TupleOflonglong> SaveAsync(Atlas.Online.Node.AffordabilityNode.OrchestrationService.Person client) {
            return base.Channel.SaveAsync(client);
        }
        
        public Atlas.Domain.DTO.PER_PersonDTO GetbyPk(long pk) {
            return base.Channel.GetbyPk(pk);
        }
        
        public System.Threading.Tasks.Task<Atlas.Domain.DTO.PER_PersonDTO> GetbyPkAsync(long pk) {
            return base.Channel.GetbyPkAsync(pk);
        }
        
        public System.Collections.Generic.List<Atlas.Domain.DTO.BankDetailDTO> GetBankDetails(System.Nullable<long> personId) {
            return base.Channel.GetBankDetails(personId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Atlas.Domain.DTO.BankDetailDTO>> GetBankDetailsAsync(System.Nullable<long> personId) {
            return base.Channel.GetBankDetailsAsync(personId);
        }
        
        public Atlas.Domain.DTO.BankDetailDTO GetBankDetail(long personId, string accountNo, bool isActive) {
            return base.Channel.GetBankDetail(personId, accountNo, isActive);
        }
        
        public System.Threading.Tasks.Task<Atlas.Domain.DTO.BankDetailDTO> GetBankDetailAsync(long personId, string accountNo, bool isActive) {
            return base.Channel.GetBankDetailAsync(personId, accountNo, isActive);
        }
        
        public Atlas.Domain.Structures.AccountVerification GetAccountVerification(string idNo, string accountNo, Atlas.Enumerators.General.BankName bank, int daysAgo) {
            return base.Channel.GetAccountVerification(idNo, accountNo, bank, daysAgo);
        }
        
        public System.Threading.Tasks.Task<Atlas.Domain.Structures.AccountVerification> GetAccountVerificationAsync(string idNo, string accountNo, Atlas.Enumerators.General.BankName bank, int daysAgo) {
            return base.Channel.GetAccountVerificationAsync(idNo, accountNo, bank, daysAgo);
        }
        
        public Atlas.Domain.Structures.AccountVerification GetAccountVerificationById(long transactionId) {
            return base.Channel.GetAccountVerificationById(transactionId);
        }
        
        public System.Threading.Tasks.Task<Atlas.Domain.Structures.AccountVerification> GetAccountVerificationByIdAsync(long transactionId) {
            return base.Channel.GetAccountVerificationByIdAsync(transactionId);
        }
        
        public Atlas.Domain.DTO.BankDetailDTO GetBankDetailByDetailId(long personId, long bankDetailId) {
            return base.Channel.GetBankDetailByDetailId(personId, bankDetailId);
        }
        
        public System.Threading.Tasks.Task<Atlas.Domain.DTO.BankDetailDTO> GetBankDetailByDetailIdAsync(long personId, long bankDetailId) {
            return base.Channel.GetBankDetailByDetailIdAsync(personId, bankDetailId);
        }
        
        public System.Nullable<long> SaveBank(long personId, Atlas.Enumerators.General.BankName bank, Atlas.Enumerators.General.BankAccountType accountType, string accountName, string accountNo, Atlas.Enumerators.General.BankPeriod accountPeriod, string branchCode) {
            return base.Channel.SaveBank(personId, bank, accountType, accountName, accountNo, accountPeriod, branchCode);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<long>> SaveBankAsync(long personId, Atlas.Enumerators.General.BankName bank, Atlas.Enumerators.General.BankAccountType accountType, string accountName, string accountNo, Atlas.Enumerators.General.BankPeriod accountPeriod, string branchCode) {
            return base.Channel.SaveBankAsync(personId, bank, accountType, accountName, accountNo, accountPeriod, branchCode);
        }
        
        public void UpdateBankDetails(long personId, long detailId, bool isActive) {
            base.Channel.UpdateBankDetails(personId, detailId, isActive);
        }
        
        public System.Threading.Tasks.Task UpdateBankDetailsAsync(long personId, long detailId, bool isActive) {
            return base.Channel.UpdateBankDetailsAsync(personId, detailId, isActive);
        }
        
        public Atlas.Online.Node.AffordabilityNode.OrchestrationService.TupleOfintstring GenerateOTP() {
            return base.Channel.GenerateOTP();
        }
        
        public System.Threading.Tasks.Task<Atlas.Online.Node.AffordabilityNode.OrchestrationService.TupleOfintstring> GenerateOTPAsync() {
            return base.Channel.GenerateOTPAsync();
        }
        
        public bool VerifyOTP(string security, int otp) {
            return base.Channel.VerifyOTP(security, otp);
        }
        
        public System.Threading.Tasks.Task<bool> VerifyOTPAsync(string security, int otp) {
            return base.Channel.VerifyOTPAsync(security, otp);
        }
        
        public string GetCompiledTemplate(Atlas.Enumerators.Notification.NotificationTemplate notificationTemplate, System.Collections.Generic.Dictionary<string, string> searchReplace) {
            return base.Channel.GetCompiledTemplate(notificationTemplate, searchReplace);
        }
        
        public System.Threading.Tasks.Task<string> GetCompiledTemplateAsync(Atlas.Enumerators.Notification.NotificationTemplate notificationTemplate, System.Collections.Generic.Dictionary<string, string> searchReplace) {
            return base.Channel.GetCompiledTemplateAsync(notificationTemplate, searchReplace);
        }
        
        public long CreatePerson(string firstName, string lastName, string idNo) {
            return base.Channel.CreatePerson(firstName, lastName, idNo);
        }
        
        public System.Threading.Tasks.Task<long> CreatePersonAsync(string firstName, string lastName, string idNo) {
            return base.Channel.CreatePersonAsync(firstName, lastName, idNo);
        }
        
        public System.Collections.Generic.List<Atlas.Enumerators.Account.Policy> CompanyPolicies(long accountId) {
            return base.Channel.CompanyPolicies(accountId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Atlas.Enumerators.Account.Policy>> CompanyPoliciesAsync(long accountId) {
            return base.Channel.CompanyPoliciesAsync(accountId);
        }
        
        public System.Collections.Generic.List<Atlas.Domain.DTO.ACC_PolicyDTO> AccountPolicies(long personId) {
            return base.Channel.AccountPolicies(personId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Atlas.Domain.DTO.ACC_PolicyDTO>> AccountPoliciesAsync(long personId) {
            return base.Channel.AccountPoliciesAsync(personId);
        }
        
        public int GetReApplyDelay(long personId) {
            return base.Channel.GetReApplyDelay(personId);
        }
        
        public System.Threading.Tasks.Task<int> GetReApplyDelayAsync(long personId) {
            return base.Channel.GetReApplyDelayAsync(personId);
        }
    }
}
