//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Accounts.Reports.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atlas.Accounts.Reports.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT t1.brnum, t1.loan, t1.client, t1.trdate, t1.usertime, t1.tramount, t1.glbank, t1.trtype , t1.trstat, COALESCE(t1.&quot;order&quot;, 0) AS &quot;order&quot;, 
        ///      COALESCE(t1.seqno, 0) AS seqno, COALESCE(t1.receiptno, 0) AS receiptno, &apos;N&apos; AS legal, r1.regiondesc, l1.loanmeth, l1.payno, l1.loandate, 
        ///      LEFT(u1.indkey_001, 4) as oper, trim(trailing FROM LEFT(u1.indkey_002, 25)) as user_name, t1.user as station, g1.bank_acct
        ///            FROM company.trans t1
        ///            JOIN company.asbranch b1 ON b1.brnum = t1.br [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlManReceiptsAedoNaedo {
            get {
                return ResourceManager.GetString("SqlManReceiptsAedoNaedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT t1.brnum, t1.loan, t1.client, t1.trdate, t1.usertime, t1.tramount, t1.glbank, t1.trtype , t1.trstat, COALESCE(t1.&quot;order&quot;, 0) AS &quot;order&quot;, 
        ///      COALESCE(t1.seqno, 0) AS seqno, COALESCE(t1.receiptno, 0) AS receiptno, &apos;N&apos; AS legal, r1.regiondesc, l1.loanmeth, l1.payno, l1.loandate, 
        ///      LEFT(u1.indkey_001, 4) as oper, trim(trailing FROM LEFT(u1.indkey_002, 25)) as user_name, t1.user as station, g1.bank_acct
        ///            FROM company.trans t1
        ///            JOIN company.asbranch b1 ON b1.brnum = t1.br [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlManReceiptsBank {
            get {
                return ResourceManager.GetString("SqlManReceiptsBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT t1.brnum, t1.loan, t1.client, t1.trdate, t1.usertime, t1.tramount, t1.glbank, t1.trtype , t1.trstat, COALESCE(t1.&quot;order&quot;, 0) AS &quot;order&quot;, 
        ///      COALESCE(t1.seqno, 0) AS seqno, COALESCE(t1.receiptno, 0) AS receiptno, &apos;N&apos; AS legal, r1.regiondesc, l1.loanmeth, l1.payno, l1.loandate, 
        ///      LEFT(u1.indkey_001, 4) as oper, trim(trailing FROM LEFT(u1.indkey_002, 25)) as user_name, t1.user as station, g1.bank_acct
        ///            FROM company.trans t1
        ///            JOIN company.asbranch b1 ON b1.brnum = t1.br [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlManReceiptsHub {
            get {
                return ResourceManager.GetString("SqlManReceiptsHub", resourceCulture);
            }
        }
    }
}
