//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.ThirdParty.CompuScan.DocumentAdministration {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentInfo", Namespace="http://schemas.datacontract.org/2004/07/Atlas.DocServer.WCF.Interface")]
    [System.SerializableAttribute()]
    public partial class DocumentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Atlas.Enumerators.Document.Category Categoryk__BackingFieldField;
        
        private long ClientPersonIdk__BackingFieldField;
        
        private string Commentk__BackingFieldField;
        
        private System.DateTime CreateDatek__BackingFieldField;
        
        private long CreatedByPersonIdk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Category>k__BackingField", IsRequired=true)]
        public Atlas.Enumerators.Document.Category Categoryk__BackingField {
            get {
                return this.Categoryk__BackingFieldField;
            }
            set {
                if ((this.Categoryk__BackingFieldField.Equals(value) != true)) {
                    this.Categoryk__BackingFieldField = value;
                    this.RaisePropertyChanged("Categoryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ClientPersonId>k__BackingField", IsRequired=true)]
        public long ClientPersonIdk__BackingField {
            get {
                return this.ClientPersonIdk__BackingFieldField;
            }
            set {
                if ((this.ClientPersonIdk__BackingFieldField.Equals(value) != true)) {
                    this.ClientPersonIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("ClientPersonIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Comment>k__BackingField", IsRequired=true)]
        public string Commentk__BackingField {
            get {
                return this.Commentk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Commentk__BackingFieldField, value) != true)) {
                    this.Commentk__BackingFieldField = value;
                    this.RaisePropertyChanged("Commentk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CreateDate>k__BackingField", IsRequired=true)]
        public System.DateTime CreateDatek__BackingField {
            get {
                return this.CreateDatek__BackingFieldField;
            }
            set {
                if ((this.CreateDatek__BackingFieldField.Equals(value) != true)) {
                    this.CreateDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("CreateDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<CreatedByPersonId>k__BackingField", IsRequired=true)]
        public long CreatedByPersonIdk__BackingField {
            get {
                return this.CreatedByPersonIdk__BackingFieldField;
            }
            set {
                if ((this.CreatedByPersonIdk__BackingFieldField.Equals(value) != true)) {
                    this.CreatedByPersonIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("CreatedByPersonIdk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
