//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.Service.AssIntService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddUserOverrideArgs", Namespace="http://schemas.datacontract.org/2004/07/Atlas.WCF.Interface")]
    [System.SerializableAttribute()]
    public partial class AddUserOverrideArgs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte NewLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionalOperatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserOperatorCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchNum {
            get {
                return this.BranchNumField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchNumField, value) != true)) {
                    this.BranchNumField = value;
                    this.RaisePropertyChanged("BranchNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte NewLevel {
            get {
                return this.NewLevelField;
            }
            set {
                if ((this.NewLevelField.Equals(value) != true)) {
                    this.NewLevelField = value;
                    this.RaisePropertyChanged("NewLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegionalOperatorId {
            get {
                return this.RegionalOperatorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionalOperatorIdField, value) != true)) {
                    this.RegionalOperatorIdField = value;
                    this.RaisePropertyChanged("RegionalOperatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserOperatorCode {
            get {
                return this.UserOperatorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserOperatorCodeField, value) != true)) {
                    this.UserOperatorCodeField = value;
                    this.RaisePropertyChanged("UserOperatorCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AssIntService.IAssThirdParty")]
    public interface IAssThirdParty {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssThirdParty/AddUserOverride", ReplyAction="http://tempuri.org/IAssThirdParty/AddUserOverrideResponse")]
        long AddUserOverride(Falcon.Service.AssIntService.AddUserOverrideArgs addUserOverrideArgs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssThirdParty/AddUserOverride", ReplyAction="http://tempuri.org/IAssThirdParty/AddUserOverrideResponse")]
        System.Threading.Tasks.Task<long> AddUserOverrideAsync(Falcon.Service.AssIntService.AddUserOverrideArgs addUserOverrideArgs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAssThirdPartyChannel : Falcon.Service.AssIntService.IAssThirdParty, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AssThirdPartyClient : System.ServiceModel.ClientBase<Falcon.Service.AssIntService.IAssThirdParty>, Falcon.Service.AssIntService.IAssThirdParty {
        
        public AssThirdPartyClient() {
        }
        
        public AssThirdPartyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AssThirdPartyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssThirdPartyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AssThirdPartyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long AddUserOverride(Falcon.Service.AssIntService.AddUserOverrideArgs addUserOverrideArgs) {
            return base.Channel.AddUserOverride(addUserOverrideArgs);
        }
        
        public System.Threading.Tasks.Task<long> AddUserOverrideAsync(Falcon.Service.AssIntService.AddUserOverrideArgs addUserOverrideArgs) {
            return base.Channel.AddUserOverrideAsync(addUserOverrideArgs);
        }
    }
}
