//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="https://www.nupay.co.za/", ConfigurationName="wsAVSRSoap")]
public interface wsAVSRSoap
{
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/accountValidate", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    System.Xml.XmlNode accountValidate(string card_acceptor, string user_id, string password, string request_id, string recieveBank, string recieveBranch, string recieveAccno, string accType, string idno, string initials, string name, string accDebits, string accCredits, string accLenght);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/accountValidate", ReplyAction="*")]
    System.Threading.Tasks.Task<System.Xml.XmlNode> accountValidateAsync(string card_acceptor, string user_id, string password, string request_id, string recieveBank, string recieveBranch, string recieveAccno, string accType, string idno, string initials, string name, string accDebits, string accCredits, string accLenght);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface wsAVSRSoapChannel : wsAVSRSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class wsAVSRSoapClient : System.ServiceModel.ClientBase<wsAVSRSoap>, wsAVSRSoap
{
    
    public wsAVSRSoapClient()
    {
    }
    
    public wsAVSRSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public wsAVSRSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public wsAVSRSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public wsAVSRSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Xml.XmlNode accountValidate(string card_acceptor, string user_id, string password, string request_id, string recieveBank, string recieveBranch, string recieveAccno, string accType, string idno, string initials, string name, string accDebits, string accCredits, string accLenght)
    {
        return base.Channel.accountValidate(card_acceptor, user_id, password, request_id, recieveBank, recieveBranch, recieveAccno, accType, idno, initials, name, accDebits, accCredits, accLenght);
    }
    
    public System.Threading.Tasks.Task<System.Xml.XmlNode> accountValidateAsync(string card_acceptor, string user_id, string password, string request_id, string recieveBank, string recieveBranch, string recieveAccno, string accType, string idno, string initials, string name, string accDebits, string accCredits, string accLenght)
    {
        return base.Channel.accountValidateAsync(card_acceptor, user_id, password, request_id, recieveBank, recieveBranch, recieveAccno, accType, idno, initials, name, accDebits, accCredits, accLenght);
    }
}
