//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx", ConfigurationName="NuPayTransactionsServiceSoap")]
public interface NuPayTransactionsServiceSoap
{
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tActivation_AC", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string ContractActivation_AC(string LendorID, string LendorType, string Username, string Password, int TransactionID);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tActivation_AC", ReplyAction="*")]
    System.Threading.Tasks.Task<string> ContractActivation_ACAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tCancellation_CC", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string ContractCancellation_CC(string LendorID, string LendorType, string Username, string Password, int TransactionID);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tCancellation_CC", ReplyAction="*")]
    System.Threading.Tasks.Task<string> ContractCancellation_CCAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tDateChange_DC", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string ContractDateChange_DC(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime NewSubmitDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tDateChange_DC", ReplyAction="*")]
    System.Threading.Tasks.Task<string> ContractDateChange_DCAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime NewSubmitDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Employe" +
        "rCodeChange_EC", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string EmployerCodeChange_EC(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewEmployerCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Employe" +
        "rCodeChange_EC", ReplyAction="*")]
    System.Threading.Tasks.Task<string> EmployerCodeChange_ECAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewEmployerCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Frequen" +
        "cyChange_FC", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string FrequencyChange_FC(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime SubmitDate, int NewFrequency);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Frequen" +
        "cyChange_FC", ReplyAction="*")]
    System.Threading.Tasks.Task<string> FrequencyChange_FCAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime SubmitDate, int NewFrequency);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tNumberChangeActivation_NA", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string ContractNumberChangeActivation_NA(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewContractNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tNumberChangeActivation_NA", ReplyAction="*")]
    System.Threading.Tasks.Task<string> ContractNumberChangeActivation_NAAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewContractNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tNumberChange_NC", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string ContractNumberChange_NC(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewContractNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tNumberChange_NC", ReplyAction="*")]
    System.Threading.Tasks.Task<string> ContractNumberChange_NCAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewContractNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tTrackingCodeChange_TC", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string ContractTrackingCodeChange_TC(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewTrackingCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tTrackingCodeChange_TC", ReplyAction="*")]
    System.Threading.Tasks.Task<string> ContractTrackingCodeChange_TCAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewTrackingCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/IdNumbe" +
        "rChange_ZC", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string IdNumberChange_ZC(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewIDNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/IdNumbe" +
        "rChange_ZC", ReplyAction="*")]
    System.Threading.Tasks.Task<string> IdNumberChange_ZCAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewIDNumber);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tPendingDateChange_FD", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string ContractPendingDateChange_FD(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime NewSubmitDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tPendingDateChange_FD", ReplyAction="*")]
    System.Threading.Tasks.Task<string> ContractPendingDateChange_FDAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime NewSubmitDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tDateChangeActivation_FA", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string ContractDateChangeActivation_FA(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime NewSubmitDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Contrac" +
        "tDateChangeActivation_FA", ReplyAction="*")]
    System.Threading.Tasks.Task<string> ContractDateChangeActivation_FAAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime NewSubmitDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entDateChange_DI", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string InstalmentDateChange_DI(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, System.DateTime NewInstalmentDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entDateChange_DI", ReplyAction="*")]
    System.Threading.Tasks.Task<string> InstalmentDateChange_DIAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, System.DateTime NewInstalmentDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entCancellation_IC", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string InstalmentCancellation_IC(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entCancellation_IC", ReplyAction="*")]
    System.Threading.Tasks.Task<string> InstalmentCancellation_ICAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entMaintenance_MI", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string InstalmentMaintenance_MI(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, System.DateTime NewInstalmentDate, string NewTrackingCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entMaintenance_MI", ReplyAction="*")]
    System.Threading.Tasks.Task<string> InstalmentMaintenance_MIAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, System.DateTime NewInstalmentDate, string NewTrackingCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entResubmit_RI", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string InstalmentResubmit_RI(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, System.DateTime NewInstalmentDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entResubmit_RI", ReplyAction="*")]
    System.Threading.Tasks.Task<string> InstalmentResubmit_RIAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, System.DateTime NewInstalmentDate);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entTrackingCodeChange_TI", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string InstalmentTrackingCodeChange_TI(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, string NewTrackingCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entTrackingCodeChange_TI", ReplyAction="*")]
    System.Threading.Tasks.Task<string> InstalmentTrackingCodeChange_TIAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, string NewTrackingCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entPreventResubmission_PR", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string InstalmentPreventResubmission_PR(string LendorID, string LendorType, string Username, string Password, int TransactionID, string Instalment);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entPreventResubmission_PR", ReplyAction="*")]
    System.Threading.Tasks.Task<string> InstalmentPreventResubmission_PRAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, string Instalment);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entResubmissionMaintenance_RM", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string InstalmentResubmissionMaintenance_RM(string LendorID, string LendorType, string Username, string Password, int TransactionID, string Instalment, System.DateTime NewInstalmentDate, string NewTrackingCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entResubmissionMaintenance_RM", ReplyAction="*")]
    System.Threading.Tasks.Task<string> InstalmentResubmissionMaintenance_RMAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, string Instalment, System.DateTime NewInstalmentDate, string NewTrackingCode);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entRecall_RE", ReplyAction="*")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    string InstalmentRecall_RE(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment);
    
    [System.ServiceModel.OperationContractAttribute(Action="https://www.nupay.co.za/wsNupayTransactions/NupayTransactionsService.asmx/Instalm" +
        "entRecall_RE", ReplyAction="*")]
    System.Threading.Tasks.Task<string> InstalmentRecall_REAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface NuPayTransactionsServiceSoapChannel : NuPayTransactionsServiceSoap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class NuPayTransactionsServiceSoapClient : System.ServiceModel.ClientBase<NuPayTransactionsServiceSoap>, NuPayTransactionsServiceSoap
{
    
    public NuPayTransactionsServiceSoapClient()
    {
    }
    
    public NuPayTransactionsServiceSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public NuPayTransactionsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NuPayTransactionsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NuPayTransactionsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string ContractActivation_AC(string LendorID, string LendorType, string Username, string Password, int TransactionID)
    {
        return base.Channel.ContractActivation_AC(LendorID, LendorType, Username, Password, TransactionID);
    }
    
    public System.Threading.Tasks.Task<string> ContractActivation_ACAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID)
    {
        return base.Channel.ContractActivation_ACAsync(LendorID, LendorType, Username, Password, TransactionID);
    }
    
    public string ContractCancellation_CC(string LendorID, string LendorType, string Username, string Password, int TransactionID)
    {
        return base.Channel.ContractCancellation_CC(LendorID, LendorType, Username, Password, TransactionID);
    }
    
    public System.Threading.Tasks.Task<string> ContractCancellation_CCAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID)
    {
        return base.Channel.ContractCancellation_CCAsync(LendorID, LendorType, Username, Password, TransactionID);
    }
    
    public string ContractDateChange_DC(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime NewSubmitDate)
    {
        return base.Channel.ContractDateChange_DC(LendorID, LendorType, Username, Password, TransactionID, NewSubmitDate);
    }
    
    public System.Threading.Tasks.Task<string> ContractDateChange_DCAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime NewSubmitDate)
    {
        return base.Channel.ContractDateChange_DCAsync(LendorID, LendorType, Username, Password, TransactionID, NewSubmitDate);
    }
    
    public string EmployerCodeChange_EC(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewEmployerCode)
    {
        return base.Channel.EmployerCodeChange_EC(LendorID, LendorType, Username, Password, TransactionID, NewEmployerCode);
    }
    
    public System.Threading.Tasks.Task<string> EmployerCodeChange_ECAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewEmployerCode)
    {
        return base.Channel.EmployerCodeChange_ECAsync(LendorID, LendorType, Username, Password, TransactionID, NewEmployerCode);
    }
    
    public string FrequencyChange_FC(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime SubmitDate, int NewFrequency)
    {
        return base.Channel.FrequencyChange_FC(LendorID, LendorType, Username, Password, TransactionID, SubmitDate, NewFrequency);
    }
    
    public System.Threading.Tasks.Task<string> FrequencyChange_FCAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime SubmitDate, int NewFrequency)
    {
        return base.Channel.FrequencyChange_FCAsync(LendorID, LendorType, Username, Password, TransactionID, SubmitDate, NewFrequency);
    }
    
    public string ContractNumberChangeActivation_NA(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewContractNumber)
    {
        return base.Channel.ContractNumberChangeActivation_NA(LendorID, LendorType, Username, Password, TransactionID, NewContractNumber);
    }
    
    public System.Threading.Tasks.Task<string> ContractNumberChangeActivation_NAAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewContractNumber)
    {
        return base.Channel.ContractNumberChangeActivation_NAAsync(LendorID, LendorType, Username, Password, TransactionID, NewContractNumber);
    }
    
    public string ContractNumberChange_NC(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewContractNumber)
    {
        return base.Channel.ContractNumberChange_NC(LendorID, LendorType, Username, Password, TransactionID, NewContractNumber);
    }
    
    public System.Threading.Tasks.Task<string> ContractNumberChange_NCAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewContractNumber)
    {
        return base.Channel.ContractNumberChange_NCAsync(LendorID, LendorType, Username, Password, TransactionID, NewContractNumber);
    }
    
    public string ContractTrackingCodeChange_TC(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewTrackingCode)
    {
        return base.Channel.ContractTrackingCodeChange_TC(LendorID, LendorType, Username, Password, TransactionID, NewTrackingCode);
    }
    
    public System.Threading.Tasks.Task<string> ContractTrackingCodeChange_TCAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewTrackingCode)
    {
        return base.Channel.ContractTrackingCodeChange_TCAsync(LendorID, LendorType, Username, Password, TransactionID, NewTrackingCode);
    }
    
    public string IdNumberChange_ZC(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewIDNumber)
    {
        return base.Channel.IdNumberChange_ZC(LendorID, LendorType, Username, Password, TransactionID, NewIDNumber);
    }
    
    public System.Threading.Tasks.Task<string> IdNumberChange_ZCAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, string NewIDNumber)
    {
        return base.Channel.IdNumberChange_ZCAsync(LendorID, LendorType, Username, Password, TransactionID, NewIDNumber);
    }
    
    public string ContractPendingDateChange_FD(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime NewSubmitDate)
    {
        return base.Channel.ContractPendingDateChange_FD(LendorID, LendorType, Username, Password, TransactionID, NewSubmitDate);
    }
    
    public System.Threading.Tasks.Task<string> ContractPendingDateChange_FDAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime NewSubmitDate)
    {
        return base.Channel.ContractPendingDateChange_FDAsync(LendorID, LendorType, Username, Password, TransactionID, NewSubmitDate);
    }
    
    public string ContractDateChangeActivation_FA(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime NewSubmitDate)
    {
        return base.Channel.ContractDateChangeActivation_FA(LendorID, LendorType, Username, Password, TransactionID, NewSubmitDate);
    }
    
    public System.Threading.Tasks.Task<string> ContractDateChangeActivation_FAAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, System.DateTime NewSubmitDate)
    {
        return base.Channel.ContractDateChangeActivation_FAAsync(LendorID, LendorType, Username, Password, TransactionID, NewSubmitDate);
    }
    
    public string InstalmentDateChange_DI(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, System.DateTime NewInstalmentDate)
    {
        return base.Channel.InstalmentDateChange_DI(LendorID, LendorType, Username, Password, TransactionID, Instalment, NewInstalmentDate);
    }
    
    public System.Threading.Tasks.Task<string> InstalmentDateChange_DIAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, System.DateTime NewInstalmentDate)
    {
        return base.Channel.InstalmentDateChange_DIAsync(LendorID, LendorType, Username, Password, TransactionID, Instalment, NewInstalmentDate);
    }
    
    public string InstalmentCancellation_IC(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment)
    {
        return base.Channel.InstalmentCancellation_IC(LendorID, LendorType, Username, Password, TransactionID, Instalment);
    }
    
    public System.Threading.Tasks.Task<string> InstalmentCancellation_ICAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment)
    {
        return base.Channel.InstalmentCancellation_ICAsync(LendorID, LendorType, Username, Password, TransactionID, Instalment);
    }
    
    public string InstalmentMaintenance_MI(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, System.DateTime NewInstalmentDate, string NewTrackingCode)
    {
        return base.Channel.InstalmentMaintenance_MI(LendorID, LendorType, Username, Password, TransactionID, Instalment, NewInstalmentDate, NewTrackingCode);
    }
    
    public System.Threading.Tasks.Task<string> InstalmentMaintenance_MIAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, System.DateTime NewInstalmentDate, string NewTrackingCode)
    {
        return base.Channel.InstalmentMaintenance_MIAsync(LendorID, LendorType, Username, Password, TransactionID, Instalment, NewInstalmentDate, NewTrackingCode);
    }
    
    public string InstalmentResubmit_RI(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, System.DateTime NewInstalmentDate)
    {
        return base.Channel.InstalmentResubmit_RI(LendorID, LendorType, Username, Password, TransactionID, Instalment, NewInstalmentDate);
    }
    
    public System.Threading.Tasks.Task<string> InstalmentResubmit_RIAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, System.DateTime NewInstalmentDate)
    {
        return base.Channel.InstalmentResubmit_RIAsync(LendorID, LendorType, Username, Password, TransactionID, Instalment, NewInstalmentDate);
    }
    
    public string InstalmentTrackingCodeChange_TI(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, string NewTrackingCode)
    {
        return base.Channel.InstalmentTrackingCodeChange_TI(LendorID, LendorType, Username, Password, TransactionID, Instalment, NewTrackingCode);
    }
    
    public System.Threading.Tasks.Task<string> InstalmentTrackingCodeChange_TIAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment, string NewTrackingCode)
    {
        return base.Channel.InstalmentTrackingCodeChange_TIAsync(LendorID, LendorType, Username, Password, TransactionID, Instalment, NewTrackingCode);
    }
    
    public string InstalmentPreventResubmission_PR(string LendorID, string LendorType, string Username, string Password, int TransactionID, string Instalment)
    {
        return base.Channel.InstalmentPreventResubmission_PR(LendorID, LendorType, Username, Password, TransactionID, Instalment);
    }
    
    public System.Threading.Tasks.Task<string> InstalmentPreventResubmission_PRAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, string Instalment)
    {
        return base.Channel.InstalmentPreventResubmission_PRAsync(LendorID, LendorType, Username, Password, TransactionID, Instalment);
    }
    
    public string InstalmentResubmissionMaintenance_RM(string LendorID, string LendorType, string Username, string Password, int TransactionID, string Instalment, System.DateTime NewInstalmentDate, string NewTrackingCode)
    {
        return base.Channel.InstalmentResubmissionMaintenance_RM(LendorID, LendorType, Username, Password, TransactionID, Instalment, NewInstalmentDate, NewTrackingCode);
    }
    
    public System.Threading.Tasks.Task<string> InstalmentResubmissionMaintenance_RMAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, string Instalment, System.DateTime NewInstalmentDate, string NewTrackingCode)
    {
        return base.Channel.InstalmentResubmissionMaintenance_RMAsync(LendorID, LendorType, Username, Password, TransactionID, Instalment, NewInstalmentDate, NewTrackingCode);
    }
    
    public string InstalmentRecall_RE(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment)
    {
        return base.Channel.InstalmentRecall_RE(LendorID, LendorType, Username, Password, TransactionID, Instalment);
    }
    
    public System.Threading.Tasks.Task<string> InstalmentRecall_REAsync(string LendorID, string LendorType, string Username, string Password, int TransactionID, int Instalment)
    {
        return base.Channel.InstalmentRecall_REAsync(LendorID, LendorType, Username, Password, TransactionID, Instalment);
    }
}
